//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieCritiqueAPI.Models
{
    
    using System.Data.Entity;

	public class ApplicationUser : User
	{
		public string userName { get; set; }
		public string password { get; set; }
	}


	public partial class MovieCritiqueEntities : DbContext
    {
	
		public MovieCritiqueEntities()
            : base("name=MovieCritiqueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
			modelBuilder.Entity<User>().ToTable("User");
			
        }
    
        public virtual DbSet<Movies> Movies1 { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
