//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieCritiqueAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int movieId { get; set; }
        public string movieName { get; set; }
        public string genres { get; set; }
        public Nullable<int> rating { get; set; }
    }
}
